### ISSUE TITLE
An error called 'Unexpected Error: Still not fine' when rebuild rar

### ISSUE THREAD

**Issue by bykzd** [srrDB/pyrescene#21]
What should I do? I don't know what the 2 number mean.

`Creating archive C:\Users\1\AppData\Local\Temp\SRR-1ykex0kl\pyReScene_compressed.r56

...       sr-nasoia.iso
Calculating the checksum

Creating archive C:\Users\1\AppData\Local\Temp\SRR-1ykex0kl\pyReScene_compressed.r57

...       sr-nasoia.iso                                               OK
Calculating the checksum
9092237465
9092237468
Still not fine :(.
Traceback (most recent call last):
  File "C:\Users\1\Downloads\pyrescene-master\rescene\srr.py", line 605, in main
    parser.exit(manage_srr(options, infolder, infiles, working_dir))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Downloads\pyrescene-master\rescene\srr.py", line 315, in manage_srr
    rescene.reconstruct(infiles[0], in_folder, out_folder, save_paths,
  File "C:\Users\1\Downloads\pyrescene-master\rescene\main.py", line 1331, in reconstruct
    srcfs = get_rar_data_object(block, blocks, src,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Downloads\pyrescene-master\rescene\main.py", line 1721, in get_rar_data_object
    compressed_rar_file_factory(block, blocks, src, in_folder, hints,
  File "C:\Users\1\Downloads\pyrescene-master\rescene\main.py", line 2048, in compressed_rar_file_factory
    return CompressedRarFile(block, blocks, src,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Downloads\pyrescene-master\rescene\main.py", line 2242, in __init__
    raise ValueError("Still not fine :(.")
ValueError: Still not fine :(.
Unexpected Error: Still not fine :(.`

**Comment by itzoke** [comment]
Try different values for the `--mt-set` option.

**Comment by bykzd** [comment]
Thank you! And maybe there is another bug since you fixed usage of -ma4 flag on compressed rars, when I rebuild another game, it will say RAR5 is not surported. I don't how to deal with it, what should I do, thank you!

**Comment by itzoke** [comment]
Try with the latest commit. That should solve the RAR5 issue. Unless the release is in fact RAR5.

**Comment by bykzd** [comment]
Seems the bug has been solved, thank you
