### ISSUE TITLE
Retag of music files still not working with python 3 and pyrescene, no problem with python 2.7

### ISSUE THREAD

**Issue by manixu** [srrDB/pyrescene#23]
Environment: Windows 10
Python 3.12.8
current pyrescene 

CMD: python d:retag.py flac_file.srr --output test 

Using flac_file.srs
Fixing flac_file.flac
From .\flac_file.flac
SRS Load Complete...          Elapsed Time: 0.00s
Track Location Complete...    Elapsed Time: 0.00s
Track Extraction Complete...  Elapsed Time: 0.32s
Traceback (most recent call last):
  File ".\resample\srs.py", line 514, in main
    sfile = sample.rebuild_sample(srs_data, tracks, attachments,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\resample\main.py", line 668, in rebuild_sample
    return flac_rebuild_sample(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\resample\main.py", line 3772, in flac_rebuild_sample
    elif (fr.block_type in bytearray(b"stu") and
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
Unexpected Error:
a bytes-like object is required, not 'str'

same CMD with python 2.7:

Using flac_file.srs
Fixing flac_file.flac
From .\flac_file.flac
SRS Load Complete...          Elapsed Time: 0.00s
Track Location Complete...    Elapsed Time: 0.01s
Track Extraction Complete...  Elapsed Time: 0.15s
Rebuild Complete...           Elapsed Time: 0.37s

File Details:   Size           CRC
                -------------  --------
Expected    :      43.491.226  F84F4BED
Actual      :      43.491.226  F84F4BED

Successfully rebuilt sample: flac_file.flac

Also release 0.7-w32 fails with:
TypeError: 'str' does not support the buffer interface

**Comment by neofright** [comment]
See https://github.com/srrDB/pyrescene/issues/2. Does this happen with the latest master?
