### ISSUE TITLE
The -z switch to point to a directory with RAR executables does not work on Linux

### ISSUE THREAD

**Issue by luckylittle** [srrDB/pyrescene#3]
Steps to reproduce:
1. Have a directory prepared by `preprardir.py` with Linux RAR executables - e.g.:
```
1997-12-29_rar202
1999-03-24_rar250
1999-10-18_rar260
2000-06-21_rar271
2001-03-02_rar280
2001-09-07_rar290
2002-05-15_rar300
2002-12-19_rar310
2003-01-15_rar311
2003-05-16_rar320
2004-01-23_rar330
2004-09-09_rar340
2004-11-03_rar341
2005-08-04_rar350
2005-10-07_rar351
2006-08-05_rar360
2007-05-22_rar370
2007-09-20_rar371
2008-09-17_rar380
2009-08-16_rar390
2009-12-12_rar391
2010-02-11_rar392
2010-03-15_rar393
2011-03-02_rar400
2011-05-29_rar401
2012-01-10_rar410
2012-02-18_rar411
2012-06-09_rar420
rarreg.key
```
2. Run `srr -z /home/$USER/Directory_with_Linux_binaries <FILE>.srr`
3. You will get an error:
```
SRR file created with pyReScene Auto 0.7.
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/srr.py", line 602, in main
    parser.exit(manage_srr(options, infolder, infiles, working_dir))
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/srr.py", line 316, in manage_srr
    options.volume is None, options.volume, rar_mt)
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 1323, in reconstruct
    in_folder, hints, auto_locate_renamed)
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 1712, in get_rar_data_object
    auto_locate_renamed))
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 2024, in compressed_rar_file_factory
    nblock, followup_src, solid=False)
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 2149, in __init__
    first_block, blocks, thread_count)
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 2395, in search_matching_rar_executable
    if rar.supports_setting_threads():
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 1795, in supports_setting_threads
    p = custom_popen([self.path()])
  File "/home/$USER/.local/lib/python3.6/site-packages/rescene/main.py", line 2779, in custom_popen
    creationflags=creationflags)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/$USER/Directory_with_Linux_binaries/2012-06-09_rar420': '/home/$USER/Directory_with_Linux_binaries/2012-06-09_rar420'
Re-creating RAR file: <FILE>.rar
Trying to rebuild compressed file <FILE>.sub.
Grabbing large enough data piece size for testing.
Trying 2012-06-09 4.20.
Unexpected Error: [Errno 2] No such file or directory: '/home/$USER/Directory_with_Linux_binaries/2012-06-09_rar420': '/home/$USER/Directory_with_Linux_binaries/2012-06-09_rar420'%                
```

**Comment by luckylittle** [comment]
My bad, this is caused by 32-bit binaries on 64-bit system:

```bash
./2012-06-09_rar420
zsh: no such file or directory: ./2012-06-09_rar420
```

```bash
file 2012-06-09_rar420
2012-06-09_rar420: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=5c19327356e4cfa8b21327382cdf808494061ea8, stripped
```
